export const checksTestIds = {
  page: 'checks-page',
  editKeywordsButton: 'edit-keywords-button',
  archiveButton: 'archive-button',
  tableList: 'check-table-list',
  stateTabs: {
    new: 'state-filter-tabs__new',
    returned: 'state-filter-tabs__returned',
    all: 'state-filter-tabs__all',
  },
  dateTabs: {
    today: 'date-filter-tabs__0',
    yesterday: 'date-filter-tabs__1',
  },
  datePickerButton: 'date-picker-button',
  editKeywordsModal: 'edit-keys-modal',
  editKeywordsModalTitle: 'edit-keys-modal__title',
  editKeywordsModalClose: 'edit-keys-modal__close',
  addKeywordButton: 'add-new-keyword-button',
  keywordList: 'checks-list',
  keywordItem: /^check-item-\d+$/,
  keywordText: 'keyword-text',
  stopTrackingButton: 'stop-tracking-button',
  stopTrackingModal: 'stop-tracking-modal',
  stopTrackingConfirmButton: 'delete-item__del-btn',
  keywordInput: 'keyword-input',
  countrySelectTrigger: 'country-select-trigger',
  countryOption: (country: string) => `country-select_option-${country}`,
  submitButton: 'submit-button',
} as const;
