export const statisticsTestIds = {
  page: 'statistics',
  title: 'statistics-title__title',
  chart: 'success-rate-chart',
  periodTabs: {
    week: 'success-rate-chart__header__tabs__7',
    month: 'success-rate-chart__header__tabs__30',
    threeMonths: 'success-rate-chart__header__tabs__84',
  },
  calendarButton: 'success-rate-chart__header__calendar-btn',
  filtersButton: 'success-rate-chart-filters-button',
} as const;

export const topKeywordsTestIds = {
  page: 'keywords-page',
  title: 'keywords-page-title__title',
  table: 'keywords-table',
  tableBody: 'keywords-table-body',
  tableHeaders: {
    country: 'keywords-table-header-country',
    traffic: 'keywords-table-header-traffic',
    createdAt: 'keywords-table-header-created_at',
    returnedAt: 'keywords-table-header-returned_at',
  },
  countryTabs: {
    all: 'keywords-country-tabs__all',
    usa: 'keywords-country-tabs__usa',
    english: 'keywords-country-tabs__english',
    europe: 'keywords-country-tabs__europe',
    latin: 'keywords-country-tabs__latin',
    asia: 'keywords-country-tabs__asia',
  },
  stateTabs: {
    all: 'keywords-filter-tabs__all',
    new: 'keywords-filter-tabs__new',
    returned: 'keywords-filter-tabs__old',
  },
  datePickerButton: 'keywords-date-picker-btn',
  translateAllToggle: 'keywords-translate-all-toggle',
  keywordRows: /^keywords-row-\d+-keyword$/,
  pagination: {
    currentPage: 'keywords-pagination__cur-page',
    totalPages: 'keywords-pagination__total-pages',
    nextButton: 'keywords-pagination__next-btn',
    previousButton: 'keywords-pagination__prev-btn',
  },
  row: (index: number) => ({
    root: `keywords-row-${index}`,
    keyword: `keywords-row-${index}-keyword`,
    geo: `keywords-row-${index}-geo`,
    traffic: `keywords-row-${index}-traffic`,
    openTopAppsButton: `keywords-row-${index}-open-top-apps-btn`,
  }),
  topAppsModal: {
    root: 'keywords-top-apps-modal',
    title: 'keywords-top-apps-modal__title',
    closeButton: 'keywords-top-apps-modal__close',
  },
} as const;

export const suggestsTestIds = {
  page: 'suggests-page',
  title: 'suggests-page-title__title',
  table: 'suggests-table',
  dateTabs: {
    all: 'suggests-date-tabs__all',
    today: 'suggests-date-tabs__0',
    yesterday: 'suggests-date-tabs__1',
  },
  datePickerButton: 'suggests-date-picker-btn',
} as const;

export const nichesTestIds = {
  page: 'niche-list-page',
  breadcrumbs: 'bread-crumbs',
  actions: 'niche-list-page__buttons-block',
  archiveButton: 'archive-button',
  createNicheButton: 'create-new-niche-button',
  content: 'niche-list-page__content',
  nicheList: 'niche-list',
  nicheListTable: 'niche-list-table',
  listTitle: 'niche-list-header-bar__title',
  sortLabel: 'niche-list-header-bar__label__title',
  search: 'niche-list-search-input',
  tableBody: 'niche-list-body',
  row: (index: number) => ({
    root: `niche-row-${index}`,
    name: `niche-cell-${index}-name`,
    module: `niche-cell-${index}-module-attribute__title`,
    countries: `niche-cell-${index}-countries`,
    keywords: `niche-cell-${index}-keywords`,
    more: `niche-cell-${index}-more-btn`,
  }),
  pagination: {
    root: 'niche-list-pagination-bar',
    rowsTrigger: 'niche-list-pagination-bar-per-page-select-trigger',
    current: 'niche-list-pagination-bar-pagination-component__cur-page',
    total: 'niche-list-pagination-bar-pagination-component__total-pages',
    previous: 'niche-list-pagination-bar-pagination-component__prev-btn',
    next: 'niche-list-pagination-bar-pagination-component__next-btn',
  },
  form: {
    modal: 'niche-form__modal',
    title: 'niche-form__modal__title',
    close: 'niche-form__modal__close',
    nameInput: 'niche-form__parent-form__input-niche',
    moduleTrigger: 'niche-form__parent-form__module-select-trigger',
    moduleContent: 'niche-form__parent-form__module-select-content',
    moduleOption: (module: 'ASO' | 'Web View') => `niche-form__parent-form__module-select_option-${module}`,
    appsButton: 'niche-form__parent-form__apps-btn',
    appCheckboxes: /^niche-form__parent-form-app-list-item-\d+-app-modal-checkbox$/,
    selectedApps: 'niche-form__parent-form__appListWrapper',
    saveApps: 'niche-form__parent-form__app-list-save-button',
    submit: 'niche-form__parent-form__submit-button',
  },
  detail: {
    page: 'niche-page',
    title: 'niche-title-niche-name',
    module: 'niche-title-module__title',
    actions: 'niche-title__dots-button',
    edit: 'niche-title__rename-button',
    export: 'niche-title__export-xlsx-button',
    moveToArchive: 'niche-title__move-to-archive-button',
    addKeyword: 'niche-title__add-keywords-button',
    table: 'niche-table__table',
    translateAll: 'niche-table__translate-all-toggle',
    selectAll: 'niche-table__select-all-checkbox-checkbox',
    addKeywords: {
      modal: 'niche-title__add-keywords-form__modal',
      title: 'niche-title__add-keywords-form__modal__title',
      close: 'niche-title__add-keywords-form__modal__close',
      manual: 'niche-title__add-keywords-form__parent-form__radioGroup__addManually',
      fromApp: 'niche-title__add-keywords-form__parent-form__radioGroup__addFromApp',
      geoTrigger: 'niche-title__add-keywords-form__parent-form__select-geo-trigger',
      geoOption: (geo: string) => `niche-title__add-keywords-form__parent-form__select-geo-option-${geo}`,
      keywordInput: 'niche-title__add-keywords-form__parent-form__input-keywords',
      submit: 'niche-title__add-keywords-form__parent-form__submit-button',
      busySelector: '[aria-busy="true"]',
    },
    row: (index: number) => ({
      root: `niche-table__row-${index}`,
      checkbox: `niche-table__row-${index}-checkbox-checkbox`,
      count: `niche-table__row-${index}-count`,
      keywords: `niche-table__row-${index}-keywords-cell`,
      copy: `niche-table__row-${index}-copy-btn`,
      translate: `niche-table__row-${index}-translate-btn`,
      actions: `niche-table__row-${index}-actions__dots__dots-button`,
      edit: `niche-table__row-${index}-actions__dots__edit-button`,
      delete: `niche-table__row-${index}-actions__dots__delete-button`,
    }),
  },
} as const;

export const performanceLocators = {
  title: 'Performance',
  periodTabs: ['1 month', '3 months', '6 months', 'All time'],
  calendarIconPath: 'button:has(svg path[d^="M21 10H3"])',
  calendar: {
    start: 'Start',
    end: 'End',
    reset: 'Reset',
    apply: 'Apply',
  },
  cards: ['card-spend', 'card-installs', 'card-proceeds'],
  chartTitle: 'Dynamics of indicators',
  tableTitle: 'Apps statistics',
  search: 'input[placeholder="Search"]',
} as const;

export const dateRangeCalendarLocators = {
  startInput: 'input[placeholder="Start"]',
  endInput: 'input[placeholder="End"]',
  resetButton: 'Reset',
  applyButton: 'Apply',
} as const;

export const sortedAppsTestIds = {
  page: 'sorted-by-apps-page',
  actions: 'sorted-by-apps-page__buttons-block',
  refreshNewButton: 'refresh-new-button',
  refreshAllButton: 'refresh-all-button',
  createAsoMobileAppButton: 'create-asomobile-app-button',
  content: 'sorted-by-apps-page__content',
  appList: 'niche-app-list',
  listTitle: 'niche-app-list-header__title',
  sortLabel: 'niche-app-list-header__label__title',
  refresh: {
    modal: 'refresh-modal',
    title: 'refresh-modal__title',
    close: 'refresh-modal__close',
    warning: 'refresh-warning-description',
    processes: 'refresh-processes-description',
    submit: 'start-refresh-button',
  },
  asoMobileCreate: {
    modal: 'create-asomobile-app-modal',
    closeButton: 'create-asomobile-app-modal__close',
    form: 'asomobile-form',
    content: 'asomobile-form-content',
    urlInput: 'asomobile-form-url-input',
    nicheTrigger: 'asomobile-form-niche-select-trigger',
    nicheContent: 'asomobile-form-niche-select-content',
    nicheOption: (label: string) => `asomobile-form-niche-select_option-${label}`,
    geosTrigger: 'asomobile-form-geos-multiselect-trigger',
    geosContent: 'asomobile-form-geos-multiselect-content',
    geoOption: (geo: string) => `asomobile-form-geos-multiselect-option-${geo}`,
    submitButton: 'asomobile-form-submit-button',
    errorMessage: 'Failed to create app. Try repeating the query',
    successMessage: 'App has been successfully created in AsoMobile',
  },
} as const;
