export const nicheResearchTestIds = {
  page: 'niche-research-page',
  createButton: 'create-niche-button',
  tabs: {
    root: 'niche-research-tabs',
    forResearch: 'niche-research-tabs__forResearch',
    researched: 'niche-research-tabs__researched',
  },
  search: 'niche-research-search',
  filters: 'niche-research-filters',
  addFilter: 'niche-research-add-filter__add',
  resetFilters: 'niche-research-add-filter__reset-all',
  filtersCatalog: {
    manager: 'undefined__option-manager__checkbox-checkbox',
    category: 'undefined__option-category__checkbox-checkbox',
    status: 'undefined__option-status__checkbox-checkbox',
    apply: 'undefined__apply-button',
  },
  activeFilters: {
    manager: 'undefined-manager__trigger',
    category: 'undefined-category__trigger',
    status: 'undefined-status__trigger',
  },
  managerFilter: {
    notAssigned: 'undefined-manager__option-not-assigned__checkbox-checkbox',
    apply: 'undefined-manager__apply-button',
  },
  table: 'niche-research-table',
  tableHeader: 'niche-research-table-header',
  tableTitle: 'niche-research-table-header__title',
  headers: {
    name: 'niche-research-table-head-name',
    description: 'niche-research-table-head-description',
    manager: 'niche-research-table-head-aso_manager',
    createdAt: 'niche-research-table-head-created_at',
    researchCreatedAt: 'niche-research-table-head-research_created_at',
  },
  pagination: {
    root: 'niche-research-pagination',
    current: /pagination-component__cur-page$/,
    total: /pagination-component__total-pages$/,
    previous: /pagination-component__prev-btn$/,
    next: /pagination-component__next-btn$/,
  },
  row: (index: number) => ({
    root: `niche-research-${index}-row`,
    name: `niche-research-${index}-name-cell`,
    category: `niche-research-${index}-category-icon`,
    descriptionCell: `niche-research-${index}-description-cell`,
    description: `niche-research-${index}-description`,
    descriptionMore: `niche-research-${index}-description-link-btn`,
    manager: `niche-research-${index}-manager-cell`,
    createdAt: `niche-research-${index}-date-cell`,
    researchCreatedAt: `niche-research-${index}-research-date-cell`,
    actions: `niche-research-${index}-actions-cell`,
    edit: `niche-research-${index}-edit-button`,
    delete: `niche-research-${index}-delete-button`,
  }),
  create: {
    root: 'create-niche-modal',
    title: 'create-niche-modal__title',
    close: 'create-niche-modal__close',
    name: 'create-niche-name-input',
    description: 'create-niche-description-textarea',
    category: 'create-niche-category-checkbox-checkbox',
    managerTrigger: 'create-niche-manager-select-trigger',
    managerValue: 'create-niche-manager-select-trigger-value',
    managerOption: /^create-niche-manager-select_option-/,
    submit: 'create-niche-submit-button',
  },
  edit: {
    root: 'edit-niche-modal',
    title: 'edit-niche-modal__title',
    close: 'edit-niche-modal__close',
    name: 'edit-niche-name-input',
    description: 'edit-niche-description-textarea',
    category: 'edit-niche-category-checkbox-checkbox',
    managerTrigger: 'edit-niche-manager-select-trigger',
    submit: 'edit-niche-submit-button',
  },
  delete: {
    confirm: 'delete-item__del-btn',
    cancel: 'delete-item__cancel-btn',
  },
} as const;
