export const productLocators = {
  technicalValue: /\b(?:error-content|undefined|NaN|null)\b|\[object Object\]/i,
  errorMessage: /Something went wrong|Something's gone wrong|Failed to load/i,
  loading: '[aria-busy="true"], [data-loading="true"], [class*="skeleton"]',
  nextPage: '[data-testid$="__next-btn"]:visible',
  previousPage: '[data-testid$="__prev-btn"]:visible',
  apps: {
    title: 'Apps',
    href: '/apps',
    archive: 'Archive',
    refresh: 'Refresh',
    searchPlaceholder: 'Search',
    periods: ['Day', 'Week', 'Month'] as const,
    views: ['App list', 'Detailed statistics'] as const,
    detailUrl: /\/apps\/[0-9a-f-]+$/i,
    appLink: 'a[href^="/apps/"]:not([href="/apps/archive"])',
    detailedRows: 'tbody tr',
    successRateColumnIndex: 2,
    metricDetails: {
      filtersButton: /^Filters:/,
      geoFilterButton: /^GEO:/,
      selectAllOption: 'undefined__option-select_all',
      totalOption: 'undefined__option-total',
      option: (value: string) => `undefined__option-${value}`,
      optionCheckbox: (value: string) => `undefined__option-${value}__checkbox-checkbox`,
      applyButton: 'undefined__apply-button',
    },
  },
  abTests: {
    title: 'A/B tests',
    href: '/ab-tests',
    create: 'Create test',
    filters: 'Filters',
    team: /^Team:/,
    app: 'App',
    testType: 'Test type',
    searchPlaceholder: 'Search',
    createUrl: /\/ab-tests\/new-test$/,
    appLink: 'a[href^="/apps/"]',
    filter: {
      definitions: [
        { name: 'Team', key: 'team', addedByDefault: true, hasSearch: false, multiSelect: false },
        { name: 'App', key: 'app', addedByDefault: true, hasSearch: true, multiSelect: true },
        { name: 'Niche', key: 'niche', addedByDefault: false, hasSearch: true, multiSelect: true },
        {
          name: 'Test type',
          key: 'testType',
          addedByDefault: true,
          hasSearch: false,
          multiSelect: true,
        },
        {
          name: 'Test result',
          key: 'testResult',
          addedByDefault: false,
          hasSearch: false,
          multiSelect: true,
        },
        {
          name: 'ASO Manager',
          key: 'asoManager',
          addedByDefault: false,
          hasSearch: false,
          multiSelect: true,
        },
      ] as const,
      trigger: (key: string) => `undefined-${key}__trigger`,
      content: (key: string) => `undefined-${key}__content`,
      search: (key: string) => `undefined-${key}__search-input`,
      selectAll: (key: string) => `undefined-${key}__option-all`,
      selectAllCheckbox: (key: string) => `undefined-${key}__option-all__checkbox-checkbox`,
      viewport: (key: string) => `undefined-${key}__scroll__viewport`,
      optionChildren: '[data-radix-scroll-area-content] > *',
      apply: (key: string) => `undefined-${key}__apply-button`,
      addTrigger: 'undefined__trigger',
      addOptionCheckbox: (key: string) => `undefined__option-${key}__checkbox-checkbox`,
      addApply: 'undefined__apply-button',
    },
    pagination: {
      currentPage: 'undefined__cur-page',
      nextPage: 'undefined__next-btn',
      rowsPerPage: 'undefined-trigger',
      rowsPerPageOption: (rows: number) => `undefined_option-${rows} tests`,
    },
    row: {
      // The frontend exposes no row test id or accessible names for the three icon actions.
      // Anchor on the stable application link and move to the owning row until semantic ids exist.
      rootFromAppLink: 'xpath=../../../../..',
      commentActionIndex: 0,
      menuActionIndex: 1,
      expandActionIndex: 2,
      viewTask: 'View task',
      variantHeaders: ['Variant', 'Content', 'Conversion rate', 'Improvement', 'Confidence'] as const,
    },
    textModal: {
      titles: ['Comment', 'Technical task'] as const,
      lowerAction: 'Edit',
      descendants: '*',
    },
    createForm: {
      uploadPrompt: 'Click to upload',
      // Initial upload has no test id; it is the first upload control in the create form.
      uploadZoneFromPrompt: 'xpath=../..',
      visibleComboboxes: 'button[role="combobox"]:visible',
      visibleOptions: '[role="option"]:visible',
      navigationButtons: 'button:not([role="combobox"]):visible',
      figmaLink: 'Figma',
      apphudLink: 'Apphud link',
      manualContentCheckbox: 'Do not upload content automatically',
    },
  },
} as const;
