export const productLocators = {
  technicalValue: /\b(?:error-content|undefined|NaN|null)\b|\[object Object\]/i,
  errorMessage: /Something went wrong|Something's gone wrong|Failed to load/i,
  loading: '[aria-busy="true"], [data-loading="true"], [class*="skeleton"]',
  nextPage: '[data-testid$="__next-btn"]:visible',
  previousPage: '[data-testid$="__prev-btn"]:visible',
  apps: {
    title: 'Apps',
    href: '/apps',
    archive: 'Archive',
    refresh: 'Refresh',
    searchPlaceholder: 'Search',
    periods: ['Day', 'Week', 'Month'] as const,
    views: ['App list', 'Detailed statistics'] as const,
    detailUrl: /\/apps\/[0-9a-f-]+$/i,
    appLink: 'a[href^="/apps/"]:not([href="/apps/archive"])',
  },
  abTests: {
    title: 'A/B tests',
    href: '/ab-tests',
    create: 'Create test',
    filters: /^Filters:/,
    team: /^Team:/,
    app: 'App',
    testType: 'Test type',
    searchPlaceholder: 'Search',
    createUrl: /\/ab-tests\/new-test$/,
    appLink: 'a[href^="/apps/"]',
  },
} as const;
