export const pushBotsLocators = {
  title: 'Push bots',
  description: 'This page contains list of pushes for all apps',
  archive: 'Archive',
  create: 'Create push',
  all: 'All',
  filters: 'Filters',
  searchPlaceholder: 'Search',
  details: 'See more',
  listEndpoint: /\/master\/api\/v1\/push\/campaigns(?:\?|$)/,
  detailUrl: /\/push-bots\/[0-9a-f-]+$/i,
  createUrl: /\/push-bots\/create$/,
  technicalValue: /\b(?:error-content|undefined|NaN|null)\b|\[object Object\]/i,
  errorMessage: /Something went wrong|Something's gone wrong|Failed to load/i,
  retry: /Repeat the request|Try again/i,
  loading: '[aria-busy="true"], [data-loading="true"], [class*="skeleton"]',
  // TODO(CRM): replace after filter builder receives a stable accessible name/test id.
  filterTrigger: '[data-testid$="__trigger"]',
  filterAdd: '[data-testid$="__add"]',
} as const;

export const outKeywordsLocators = {
  title: 'Out keywords',
  description: 'This page contains a list of out keyword for all apps.',
  settings: 'Settings',
  deleteAll: 'Delete all installs',
  today: 'Today',
  yesterday: 'Yesterday',
  filters: 'Filters',
  searchPlaceholder: 'Search',
  emptyTitle: 'No out keywords',
  emptyDescription: 'All keywords are pushed successfully',
  listEndpoint: /\/master\/api\/v1\/push\/out-keywords\/apps(?:\?|$)/,
  settingsEndpoint: /\/master\/api\/v1\/dashboards\/info(?:\?|$)/,
  settingsFields: 'input, textarea',
  saveSettings: /Save|Apply/i,
  technicalValue: pushBotsLocators.technicalValue,
  errorMessage: pushBotsLocators.errorMessage,
  retry: pushBotsLocators.retry,
  loading: pushBotsLocators.loading,
  filterTrigger: pushBotsLocators.filterTrigger,
  filterAdd: pushBotsLocators.filterAdd,
} as const;
