export const subscriptionsTestIds = {
  pageBody: 'body',
  pageScrollCandidates: ':scope, *',
  page: 'subscriptions-page',
  title: 'subscriptions-page-title__title',
  tabs: {
    daily: 'subscriptions-tabs__dailyStatistics',
    dynamics: 'subscriptions-tabs__dynamicsOfIndicators',
  },
  dailyStatisticsTab: 'daily-statistics-tab',
  dailyStatisticsContent: 'daily-statistics-content',
  dailyDates: {
    root: 'daily-statistics-dates-filter',
    presets: /^daily-statistics-dates-filter__tabs__\d{4}-\d{2}-\d{2}$/,
    calendarButton: 'button:not([role="tab"])',
    dialog: 'dialog',
    applyButton: 'daily-statistics-dates-filter__date-picker__header__apply-btn',
  },
  cardsList: 'daily-statistics-cards-list',
  cards: /^daily-statistics-cards-list-card-\d+$/,
  cardsScrollCandidates: ':scope, *',
  table: 'subscriptions-table',
  tableControls: {
    descendants: '*',
    search: 'niche-list-search-input',
    sortableColumn: (column: string) => `undefined-${column}`,
    perPage: 'undefined-per-page-select-trigger',
    perPageOption: (rows: number) => `undefined-per-page-select_option-${rows} rows`,
    previousPage: 'undefined-pagination-component__prev-btn',
    nextPage: 'undefined-pagination-component__next-btn',
    currentPage: 'undefined-pagination-component__cur-page',
    totalPages: 'undefined-pagination-component__total-pages',
    appStoreLinkName: 'AppStore',
  },
  retryButtonName: /Repeat the request/i,
  filtersButton: 'daily-statistics-filters-count-button',
  filters: {
    root: 'daily-statistics-applied-filters',
    addFilter: {
      trigger: 'daily-statistics-filter-popover__trigger',
      content: 'daily-statistics-filter-popover__content',
      appOption: 'daily-statistics-filter-popover__option-App',
      applyButton: 'daily-statistics-filter-popover__apply-button',
    },
    app: {
      trigger: 'daily-statistics-visible-filter-App__trigger',
      content: 'daily-statistics-visible-filter-App__content',
      allOption: 'daily-statistics-visible-filter-App__option-all',
      individualOptions: /^daily-statistics-visible-filter-App__option-(?!all$)(?!.*__checkbox$).+$/,
      applyButton: 'daily-statistics-visible-filter-App__apply-button',
      activeFilter: 'daily-statistics-visible-filter-App__active-filter',
      resetButton: 'daily-statistics-visible-filter-App__active-filter__close-btn',
      expectedAllLabel: /^App:\s*All$/,
      partialLabel: /^App:\s*\S/,
      allLabel: 'All',
    },
  },
  dynamics: {
    tab: 'dynamics-of-indicators-tab',
    content: 'dynamics-of-indicators-content',
    dates: {
      root: 'dynamics-of-indicators-dates-filter',
      week: 'dynamics-of-indicators-dates-filter__tabs__week',
      month: 'dynamics-of-indicators-dates-filter__tabs__month',
      threeMonths: 'dynamics-of-indicators-dates-filter__tabs__three_months',
      calendarButton: 'button:not([role="tab"])',
      applyButton: 'dynamics-of-indicators-dates-filter__date-picker__header__apply-btn',
    },
    filtersButton: 'dynamics-of-indicators-filters-button',
    filtersRoot: 'dynamics-of-indicators-applied-filters',
    cardsList: 'dynamic-of-indicators-cards-list',
    cardsViewport: 'dynamic-of-indicators-cards-list-scroll__viewport',
    cards: /^dynamic-of-indicators-cards-list-card-\d+$/,
    chart: 'dynamic-of-indicators-chart',
    indicators: {
      trigger: 'dynamics-of-indicators-visible-filter-Indicators__trigger',
      activeFilter: 'dynamics-of-indicators-visible-filter-Indicators__active-filter',
      content: 'dynamics-of-indicators-visible-filter-Indicators__content',
      allOption: 'dynamics-of-indicators-visible-filter-Indicators__option-all',
      option: (indicator: string) => `dynamics-of-indicators-visible-filter-Indicators__option-${indicator}`,
      applyButton: 'dynamics-of-indicators-visible-filter-Indicators__apply-button',
    },
    addFilter: {
      trigger: 'dynamics-of-indicators-filter-popover__trigger',
      content: 'dynamics-of-indicators-filter-popover__content',
      appOption: 'dynamics-of-indicators-filter-popover__option-App',
      applyButton: 'dynamics-of-indicators-filter-popover__apply-button',
    },
    app: {
      trigger: 'dynamics-of-indicators-visible-filter-App__trigger',
      content: 'dynamics-of-indicators-visible-filter-App__content',
      option: (appId: string) => `dynamics-of-indicators-visible-filter-App__option-${appId}`,
      applyButton: 'dynamics-of-indicators-visible-filter-App__apply-button',
      activeFilter: 'dynamics-of-indicators-visible-filter-App__active-filter',
      resetButton: 'dynamics-of-indicators-visible-filter-App__active-filter__close-btn',
    },
  },
} as const;
