export const taskGeneratorLocators = {
  route: '/task-generator',
  title: 'Task generator',
  apiDocuments: /\/master\/api\/v1\/task-generator\/documents/,
  form: 'undefined__form',
  countInput: 'undefined__count-input',
  commentInput: 'undefined__comment-textarea',
  generateButton: 'undefined__submit-button',
  historyTitle: 'History of generations',
  search: 'niche-app-list-search-input',
  table: 'undefined__main',
  tableBody: 'undefined__table-body',
  rows: '[data-testid^="undefined-row-"]',
  firstName: 'undefined-name-cell-0',
  firstCheckbox: 'undefined-id-cell-0__checkbox-checkbox',
  selectAll: 'undefined__select-all-checkbox-checkbox',
  rowCheckboxes: '[data-testid^="undefined-id-cell-"][data-testid$="__checkbox-checkbox"]',
  docxActions: '[data-testid^="undefined-actions-cell-"][data-testid$="-add-btn"]',
  statusTrigger: 'undefined__header-table__filter-status__trigger',
  dateSort: 'undefined__header-table-date',
  paginationRows: 'niche-app-list-perpage-select-trigger',
  emptyPattern: /Nothing was found|No data|not found/i,
  errorPattern: /Something went wrong|Failed|error/i,
  technicalValue: /\b(?:undefined|NaN|null)\b|\[object Object\]/i,
} as const;
